conditional/blueprints/major_project_submission.py
=> Add Non-Blank Requirement to Major Projects

conditional/templates/attendance_cm.html, conditional/templates/dashboard.html, conditional/templates/intro_eval_slideshow.html, conditional/templates/intro_evals.html, conditional/templates/nav.html, conditional/templates/spring_eval_slideshow.html, conditional/templates/spring_evals.html
=> Changed committee to directorship

conditional/templates/attendance_cm.html, conditional/templates/attendance_hm.html, conditional/templates/attendance_ts.html, conditional/templates/conditional.html, conditional/templates/dashboard.html, conditional/templates/financial.html, conditional/templates/housing.html, conditional/templates/intro_eval_slideshow.html, conditional/templates/intro_evals.html, conditional/templates/intro_evals_form.html, conditional/templates/major_project_submission.html, conditional/templates/member_management.html, conditional/templates/spring_eval_slideshow.html, conditional/templates/spring_evals.html
=> Added titles to all webpages.

conditional/templates/dashboard.html, conditional/templates/nav.html
Fixes #40 
Not sure if we want to change the urls and such too, or just where it's easily publicly seen.
=> Changed Spring Evaluations to Membership Evaluations

conditional/blueprints/member_management.py
Hotfix branch for a critical fid deletion bug.
=> Hotfix v1.01a

conditional/templates/major_project_submission.html
=> Add Major Project Name Form Length

.travis.yml, README.md
Linting our code is important. I'd like to add TravisCI as a check to make sure that we aren't accepting code that will break our linting and other guidelines.
=> Add TravisCI Support

conditional/blueprints/conditional.py, conditional/templates/conditional.html, frontend/javascript/modules/conditionalActions.js, frontend/javascript/modules/conditionalForm.js, frontend/javascript/modules/majorProjectStatus.js, frontend/javascript/modules/memberSelect.js, frontend/stylesheets/components/_flat-buttons.scss, frontend/stylesheets/components/_select.scss, frontend/stylesheets/pages/_evals.scss
This PR adds the ability for the evals director to create conditionals and pass/fail/delete existing conditionals. Fixes https://github.com/ComputerScienceHouse/conditional/issues/49.
=> Add conditional creation and actions

conditional/blueprints/dashboard.py
=> Don't show time for directorship meeting attends

conditional/util/ldap.py
=> Fix LDAP set field NoneType

conditional/util/housing.py
Fix population of Housing Queue
Coop commit untested
=> Fix housing queue

frontend/javascript/modules/table.js
=> Add way to ignore sorting order for tables

.sass-lint.yml, conditional/blueprints/intro_evals.py, conditional/templates/intro_eval_slideshow.html, frontend/javascript/modules/conditionalForm.js, frontend/javascript/modules/presentation.js, frontend/stylesheets/app.scss, frontend/stylesheets/components/_reveal.scss, frontend/stylesheets/components/reveal/_white.scss, frontend/stylesheets/presentations.scss, gulpfile.js/config.json, package.json
Fixes #5 
I made the frontend for the intro evals slideshow using reveal.js and the backend already in place. Users can now be vote on, and the results are sent to conditional.
=> Created and styled intro evals slideshow

conditional/blueprints/spring_evals.py, conditional/templates/spring_eval_slideshow.html, frontend/javascript/modules/presentation.js, frontend/stylesheets/components/reveal/_white.scss
Fixes #4 
Made the Spring Evals slideshow, mostly based on the Intro Evals slideshow. Has the ability to show multiple major projects passed, and won't show a user if their status is "Pending", i.e. not previously passed/failed.
=> Created spring evals slideshow

conditional/blueprints/cache_management.py, conditional/util/ldap.py
Allows for members of the rtp group to restart this application through the web,
rather than restarting all of apache
=> Add route for application restart

conditional/__init__.py, conditional/templates/base.html, frontend/stylesheets/partials/_global.scss
I'm not sure this visually looks the best that it could. But I think that this is an important thing to have in order to know what version of conditional is actively being run in a wsgi process.
=> Add git revision footer to every non-preso page

conditional/blueprints/housing.py, conditional/blueprints/member_management.py, conditional/templates/housing.html, conditional/util/housing.py, frontend/javascript/exceptions/housingException.js, frontend/javascript/modules/housingEdit.js, frontend/stylesheets/pages/_housing.scss
Fixes #22 
Adds the ability for the Evaluations Director to quickly go down the housing board and modify rooms in-line on the Housing page.
=> In-Line Housing Update Functionality

conditional/__init__.py, conditional/templates/errors.html, config.sample.py, frontend/javascript/app.js, frontend/javascript/modules/errorReport.js, frontend/stylesheets/pages/_errors.scss, frontend/stylesheets/partials/_global.scss, package.json, requirements.txt
Adds frontend and backend error reporting via Sentry.
=> Add Sentry error reporting

conditional/blueprints/intro_evals.py, conditional/blueprints/spring_evals.py
This is based on a conversation with @mbillow about not showing directorship meetings and technical seminars whose attendance hasn't been approved yet.
=> Hide non-approved meetings and seminars from slideshows

conditional/util/ldap.py
This change is going to be reflected in the LDAP schema within the next few
days. This is in preparation to be merged and patched in when that happens.
=> Rename Evaulations to Evaluations

frontend/javascript/modules/newYear.js
=> Pass cookies through newYear requests

conditional/blueprints/member_management.py, frontend/javascript/modules/newYear.js
=> Conditional 1.5.1

conditional/blueprints/dashboard.py, conditional/templates/dashboard.html, conditional/util/member.py
Much fast. Such work. 🐶 
The original queries weren't working... So I rewrote them to be one query and so they actually work.
=> Optimized Committee Meeting Query

conditional/blueprints/intro_evals.py
- Optimize Intro Evals Seminar Query
=> Conditional 1.5.2

requirements.txt
Using csh_ldap 2.0.2 so that we can move conditional out of read only
=> Using csh_ldap 2.0.2

conditional/__init__.py, conditional/blueprints/attendance.py, conditional/blueprints/cache_management.py, conditional/blueprints/co_op.py, conditional/blueprints/conditional.py, conditional/blueprints/dashboard.py, conditional/blueprints/housing.py, conditional/blueprints/intro_evals.py, conditional/blueprints/intro_evals_form.py, conditional/blueprints/logs.py, conditional/blueprints/major_project_submission.py, conditional/blueprints/member_management.py, conditional/blueprints/slideshow.py, conditional/blueprints/spring_evals.py
There was an issue with submitting forms due to not passing in the uid, now it will actually pass in the username to allow for full logging
=> Fixing Logging to allow submission of Forms

conditional/templates/dashboard.html
- you know I'm a ho for those squars
- fixes: #179 
I'm no web developer but I figure that's all that needs to change, whomst is to say
=> Change 'On-floor' label to 'On-floor Status'

conditional/blueprints/attendance.py, conditional/templates/dashboard.html, conditional/templates/intro_eval_slideshow.html, conditional/templates/intro_evals.html, conditional/templates/spring_evals.html, frontend/stylesheets/pages/_evals.scss
Changes:
- Fixes attendance page issue. Fixes #177 
- Removes freshman project when it's `Pending` in presentation as it generally means `excused`
- Makes date format on Dashboard no longer show timestamp
- Fixes issue with firefox dropdowns. Fixes #178
=> Fixing Attendance issue and Style Changes

requirements.txt
There are some packages that need some updating, let's just bump them up pls
=> Updating Packages

Dockerfile
Setting the timezone so that Conditional pulls correct dates and times for viewing
Fixes #189
=> Setting docker timezone

conditional/templates/intro_eval_slideshow.html, conditional/templates/spring_eval_slideshow.html, frontend/stylesheets/components/reveal/_white.scss
Simply adds photos to the presentations
=> Adding Presentation Photos

conditional/templates/intro_evals.html, conditional/templates/spring_evals.html
=> Data Sort on Tables

conditional/blueprints/co_op.py
So that other services can check if someone is on co-op, add to the co-op groups
=> Adding to ldap group when putting in co-op

conditional/blueprints/co_op.py, conditional/templates/nav.html
Currently anyone could submit the form, only work for current_students
=> Only allow current students to list co-ops

conditional/util/member.py
Fix the overcounting of voting members by only checking freshmen data from the current year
=> Only freshmen from this year are voting

conditional/models/models.py, conditional/templates/attendance_cm.html, migrations/versions/3eaae92ce6b3_ad_hoc.py
Adding an option for ad-hoc attendance
=> Adhoc attendance

conditional/__init__.py, config.env.py, requirements.txt
Adding the new sentry SDK to track python errors
=> Adding sentry SDK

config.env.py
Need a legacy DSN for Javascript tracking
=> Adding Legacy DSN var

conditional/templates/attendance_history.html, conditional/templates/attendance_hm.html, conditional/templates/base_protected.html, conditional/templates/co_op_management.html, conditional/templates/conditional.html, conditional/templates/dashboard.html, conditional/templates/errors.html, conditional/templates/financial.html, conditional/templates/housing.html, conditional/templates/intro_eval_slideshow.html, conditional/templates/intro_evals.html, conditional/templates/intro_evals_form.html, conditional/templates/logs.html, conditional/templates/member_management.html, conditional/templates/nav_protected.html, conditional/templates/new_year.html, conditional/templates/spring_eval_slideshow.html, conditional/templates/spring_evals.html
=> Use protected and not protected templates for lockdown

.travis.yml
=> Add docker to travis

Dockerfile, conditional/blueprints/dashboard.py, conditional/templates/dashboard.html, conditional/util/member.py
=> Fix 500 on dashboard for non-upgraded accounts

conditional/templates/dashboard.html, conditional/util/member.py
https://cshrit.slack.com/archives/CV0REE4JE/p1631659300194600
It doesn't exist, I got very confused when I saw it because it was never discussed. Apparently its been gone for a while, so why not just remove it from the dashboard?
=> Remove Freshman Project in Dashboard

package-lock.json
This was never saved to the repo, so once a new build was done and things weren't saved everything got destroyed.
I have no idea how this happened, but its fixed now. Pls move to develop and master because prod is 💀 
Don't really understand how/why the old one closed, I fucked up a lot of stuff in git and it just chose to drop off
=> Add Package Lock

package-lock.json
=> Fix Lock Version

package.json
conditional-dev works, so I believe its ready to go
=> Merge Develop to Master: package-lock.json

config.env.py
=> packet glue but again

conditional/util/auth.py
=> packet glue but even more
