- conditional/blueprints/dashboard.py
- conditional/templates/dashboard.html
Fixes #29 
This is *an* approach. This way we can keep both the left and right columns of the dashboard info at 3 rows, so it looks more consistent. Thoughts?
> Housing queue position now shows a more intuitive message.

- conditional/blueprints/intro_evals.py
- conditional/templates/intro_evals.html
- conditional/templates/spring_evals.html
- frontend/stylesheets/pages/_evals.scss
- Fix dropdown display login on intro evals page.
- Actually display pending results instead of 65535
- Match freshmen project pending status to pending packet.
- Fix adding issues when dropdown is hidden.
> Improve Evals Pages

- conditional/blueprints/attendance.py
- conditional/blueprints/slideshow.py
- conditional/models/migrate.py
- conditional/models/models.py
I was inconsistent with usage of utcnow vs now. We should just use servertime.
> utcnow -> now

- .gitignore
Minor detail, but contributors following the instructions on the readme will see `.conditionalenv` in their git status, which prevents the use of `git commit .` and could easily be committed by accident.
Since this is the default virtualenv folder used in the readme, I think it's worth adding to the gitignore.
> Add virtualenv dir from readme to gitignore

- conditional/blueprints/member_management.py
Now works as advertised for onfloor status changes!!!!!!
> Actually add/remove onfloor status like advertised

- conditional/blueprints/member_management.py
- conditional/util/ldap.py
Currently there is no check to prevent making another OnFloorStatusAssigned
object if a member is edited in the Member Management page.
I'll ping in this thread once I've sufficiently tested this.
> Stop Duplication of OnFloorStatusAssigned Objects

- conditional/templates/intro_eval_slideshow.html
- frontend/javascript/modules/conditionalForm.js
- frontend/javascript/modules/presentation.js
- frontend/stylesheets/components/_reveal.scss
- frontend/stylesheets/components/reveal/_white.scss
The presentation currently advances (goes to next slide, marks and disables button as "Conditionaled") on just closing the conditional modal, regardless of if it successfully went through, or if there was even any data entered or submitted. I moved the functionality to advance through the slides to the success callback for the modal, so that it only executes on a successful submission of a conditional.
> Fixed conditional submission and added missed packet signatures

- app.py
- conditional/__init__.py
- conditional/blueprints/attendance.py
- conditional/blueprints/cache_management.py
- conditional/blueprints/conditional.py
- conditional/blueprints/dashboard.py
- conditional/blueprints/housing.py
- conditional/blueprints/intro_evals.py
- conditional/blueprints/major_project_submission.py
- conditional/blueprints/member_management.py
- conditional/blueprints/spring_evals.py
- conditional/util/auth.py
- conditional/util/flask.py
- conditional/util/housing.py
- conditional/util/ldap.py
- conditional/util/member.py
- config.sample.py
- requirements.txt
Solves #89 
pyldap => csh_ldap
> Move to new CSH LDAP ORM

- conditional/util/ldap.py
Due to circular imports I left out adding a function to `cache_management.py` which calls `ldap.py` methods and just use the methods in `ldap.py` to clear cache. If we need methods to clear specific caches in our application we can add them to `cache_management.py` and call them but `ldap.py` calling a method from `cache_management.py` which calls a method from `ldap.py` creates a circular import and seems silly
> Fix #111 by adding cache invalidation to cached ldap queries

- frontend/javascript/modules/attendanceForm.js
Now that attendance can be modified, there should not be a warning that attendance cannot be changed.
> removed initial attendance submission warning

- conditional/templates/major_project_submission.html
This will be useful to guide members for writing better descriptions of their
projects and listing out things like GitHub repos associated with the project.
The text is currently up for debate, but regardless of what it says in the end I think we should be implementing something like this.
> Add placeholder text for the major project form

- conditional/blueprints/housing.py
- conditional/blueprints/member_management.py
- conditional/templates/member_management.html
- conditional/templates/new_year.html
- conditional/util/ldap.py
- frontend/javascript/modules/newYear.js
- frontend/stylesheets/pages/_management.scss
- frontend/stylesheets/partials/_global.scss
The evaluations director now has a simple, easy to follow flow for clearing the active group, removing everyone from their rooms, pruning the current students group, and then filling out the housing roster. 
Fixes #140
> New Year Flow

- conditional/blueprints/member_management.py
We can't have empty groups and the ED should always be active during the transition.
> Don't Remove Eval Director from Active Group

- conditional/blueprints/spring_evals.py
- conditional/util/member.py
This probably works. But it's currently untested
> Fix House Meeting Attendance Status Display

- conditional/blueprints/intro_evals.py
When a member has a house meeting absence excused it should not count
against them.
> Fix HM Attendance on Intro Evals Page

- conditional/templates/intro_evals.html
- conditional/templates/spring_evals.html
- frontend/javascript/modules/evalToggle.js
Adds a table view that you can toggle into from evaluations pages. 
I guess this fixes #128 too.
> Table Views for Evals Pages

- conditional/blueprints/member_management.py
As of 2018-09-01 the ritDn field in LDAP contains data in the following
format:
ABC1234
Rather than the older (and incorrect in terms of DNs) format:
uid=ABC1234,ou=people,dc=rit,dc=edu
This fixes an issue where accounts created under the new FreeIPA
infrastructure would populate the ritDn field with the uid of the member
in respect to their RIT account, but not in a full dn format.
Since this change is trivial, looking for review from either Marc or Devin (or anyone).
> Fix 'ritDn' parser for active member export button

- conditional/templates/intro_eval_slideshow.html
- conditional/templates/spring_eval_slideshow.html
- frontend/javascript/modules/presentation.js
Fixes error in screenshot above where names that are too long clip the pass/fail buttons on the intro/spring evaluations slideshows.
> Fixing multi-line names from clipping content in presentations

- conditional/templates/dashboard.html
I don't think this should be hidden.
It being hidden makes doing constitution things harder and there's no reason for it to be hidden.
> Make the number of active members visible

- conditional/blueprints/intro_evals.py
- conditional/models/models.py
- conditional/templates/dashboard.html
- conditional/templates/intro_eval_slideshow.html
- conditional/templates/intro_evals.html
For Freshman Evals, Conditional still showed a requirement of 10
directorships isntead of the new 6. This fixes that for the visual "/6"
and the check for a check or X mark.
@Lontronix
> Change 10 to 6 for Freshman Directorships

- conditional/__init__.py
- conditional/templates/nav.html
> packet glue but again (navbar yippee)
